// Generated by CoffeeScript 1.7.1
(function(window) {
  var elms, makeBtns, slice;
  slice = Array.prototype.slice;
  if (navigator.userAgent.indexOf('Macintosh') > -1) {
    makeBtns = slice.call(document.querySelectorAll('.make-qrcode'));
    makeBtns.forEach(function(btn) {
      return btn.setAttribute('i18n-content', 'qr_make_mac_btn');
    });
  }
  elms = document.querySelectorAll('[i18n-content]');
  elms = slice.call(elms);
  elms.forEach(function(elm) {
    return elm.innerHTML = chrome.i18n.getMessage(elm.getAttribute('i18n-content')) || 'Error:No Message';
  });
  elms = document.querySelectorAll('[i18n-value]');
  elms = slice.call(elms);
  return elms.forEach(function(elm) {
    var attrs;
    attrs = elm.getAttribute('i18n-value').split(';');
    return attrs.forEach(function(attr) {
      attr = attr.split(':');
      if (attr.length > 1) {
        return elm.setAttribute(attr[0].trim(), chrome.i18n.getMessage(attr[1].trim()) || 'Error:No values');
      }
    });
  });
})(window);


//# sourceMappingURL=i18n.map
