// Generated by CoffeeScript 1.10.0
define(function(require) {
  var init;
  init = function(cat, parts) {
    if (parts) {
      $('html, body').animate({
        scrollTop: $("#" + parts).offset().top - 70
      }, 500);
    }
  };
  return {
    init: init
  };
});


//# sourceMappingURL=help-page.js.map
