// Generated by CoffeeScript 1.10.0
define(function(require) {

  /**
   * Function to generate trs html
   * accepts rules
   */
  var nodataTpl, rulesTpl;
  rulesTpl = (function() {
    var deleteText, tpl;
    deleteText = chrome.i18n.getMessage('opt_delete_text');
    tpl = '<tr>\n   <td><input type="checkbox" value="{{ruleId}}"></td>\n   <td title="{{title}}">{{rule}}</td>\n   <td class="delete">#{del}</td>\n</tr>';
    tpl = tpl.replace('#{del}', deleteText);
    return function(arr) {
      var res;
      res = '';
      arr.forEach(function(a) {
        res += tpl.replace(/\{\{(\w+)\}\}/g, function($0, $1) {
          if ($1 === 'del') {
            return deleteText;
          }
          return a[$1] || $1;
        });
      });
      return res;
    };
  })();

  /**
   * String of no data tr
   * @return {[type]} [description]
   */
  nodataTpl = (function() {
    return "<tr nodata>" + "<td colspan='3' class='text-center'>" + ("" + (chrome.i18n.getMessage('opt_no_rules'))) + "</td>" + "</tr>";
  })();
  return {
    rulesTpl: rulesTpl,
    nodataTpl: nodataTpl
  };
});


//# sourceMappingURL=tpl.js.map
