// Generated by CoffeeScript 1.9.2
define(function(require) {

  /**
   * Function to generate trs html
   * accepts rules
   */
  var nodataTpl, rulesTpl;
  rulesTpl = (function() {
    var deleteText, tpl;
    deleteText = chrome.i18n.getMessage('opt_delete_text');
    tpl = '<tr>\n   <td><input type="checkbox" value="{{rule}}"></td>\n   <td title="{{rule}}">{{rule}}</td>\n   <td class="delete">#{del}</td>\n</tr>';
    tpl = tpl.replace('#{del}', deleteText);
    return function(arr) {
      var res;
      res = '';
      arr.forEach(function(a) {
        res += tpl.replace(/\{\{\w+\}\}/g, a);
      });
      return res;
    };
  })();

  /**
   * String of no data tr
   * @return {[type]} [description]
   */
  nodataTpl = (function() {
    return "<tr nodata>" + "<td colspan='3' class='align-center'>" + ("" + (chrome.i18n.getMessage('opt_no_rules'))) + "</td>" + "</tr>";
  })();
  return {
    rulesTpl: rulesTpl,
    nodataTpl: nodataTpl
  };
});
