// Generated by CoffeeScript 1.9.2
define(function(require) {
  var getCustomFavorGsearch, init, modal, updateGhostText, utils;
  utils = require('common/utils');
  modal = require('js/component');
  init = function(cat) {
    var onoff;
    onoff = utils.getLocal('onoff', 'o');
    $('#switch-google').prop('checked', !!onoff.gsearch);
    $('#switch-gstatic').prop('checked', !!onoff.gstatic);
    return updateGhostText(getCustomFavorGsearch());
  };
  updateGhostText = function(host) {
    $('#custom-favor-gsearch').text(host);
    $('#custom-favor-gsearch-wrapper').prop('hidden', !host);
  };
  getCustomFavorGsearch = function() {
    var host;
    host = utils.getLocal('gsearch', 'a');
    host = host ? host[0] || '' : '';
    return host.slice(4, -5);
  };
  $('#switch-google').on('change', function() {
    utils.setSwitch('gsearch', !!this.checked);
  });
  $('#switch-gstatic').on('change', function() {
    utils.setSwitch('gstatic', !!this.checked);
  });
  $('#preferred-google').on('keyup', function(e) {
    if (e.keyCode === 13) {
      $('#input-dialog-wrapper .js-btn-ok').click();
    }
  });
  $('#gsearch-rule-switch').on('click', '.js-add-favor-gsearch', function() {
    var $wrapper;
    $('#preferred-google').val(getCustomFavorGsearch());
    $wrapper = $('#input-dialog-wrapper');
    $(document.body).addClass('ovHidden');
    $wrapper.prop('hidden', false);
    $wrapper.addClass('fadeInDown');
    setTimeout(function() {
      $('#preferred-google').focus();
    }, 210);
  });
  $('#input-dialog-wrapper .js-btn-ok').on('click', function() {
    var arr, host, i;
    host = $.trim($('#preferred-google').val());
    if (host === '') {
      utils.setLocal('gsearch');
      updateGhostText('');
      modal.hideDlg('#input-dialog-wrapper');
      return;
    }
    host = host.toLowerCase();
    i = host.indexOf('\/\/');
    if (i !== -1) {
      host = host.substr(i + 2);
    }
    i = host.indexOf('\/');
    if (i !== -1) {
      host = host.substr(0, i);
    }
    if (utils.isIp(host) || utils.isHost(host)) {
      arr = host.split('.');
      if (arr.length === 2 && arr[0] === 'google') {
        host = "www." + host;
      }
      updateGhostText(host);
      utils.setLocal('gsearch', ["*://" + host + "/url*"]);
      modal.hideDlg('#input-dialog-wrapper');
    } else {
      modal.showTip($('#preferred-google'), utils.i18n('opt_errtip_host'));
    }
  });
  return {
    init: init
  };
});


//# sourceMappingURL=utility-page.js.map
