// Generated by CoffeeScript 1.9.2
define(function() {
  var QR_API_HOST, QR_API_URL;
  QR_API_HOST = 'api.qrserver.com';
  QR_API_URL = 'http://api.qrserver.com/v1/create-qr-code/?size=200x200&data=%s';
  return {
    QR_API_HOST: QR_API_HOST,
    QR_API_URL: QR_API_URL
  };
});


//# sourceMappingURL=vars.js.map
