// Generated by CoffeeScript 1.10.0

/**
 * all rules gather together to be a collection
 */
var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

(function(root, factory) {
  if (typeof define === 'function' && (define.amd || define.cmd)) {
    define(function() {
      return factory(root);
    });
  } else if (typeof exports === 'object') {
    module.exports = factory(root);
  } else {
    root.collection = factory(root);
  }
})(this, function(root) {
  var addRule, cats, collection, eachRule, getConfig, getLocal, getRule4Show, getRules, getRules4Show, getSwitch, hasCat, hasRule, initCollection, isRestoring, removeLocal, removeRule, saveRule, setConfig, setLocal, setRestoreStatus, setSwitch;
  collection = {};
  cats = ['block', 'hsts', 'hotlink', 'log', 'custom', 'gsearch'];
  initCollection = function() {
    var cat, hasInvalidRule, i, k, len, rules, v;
    for (i = 0, len = cats.length; i < len; i++) {
      cat = cats[i];
      hasInvalidRule = false;
      if (cat === 'custom') {
        rules = JSON.parse(localStorage.getItem(cat) || '{}');
        for (k in rules) {
          v = rules[k];
          if (!v) {
            hasInvalidRule = true;
            delete rules[k];
          }
        }
        collection[cat] = rules;
      } else {
        rules = JSON.parse(localStorage.getItem(cat) || '[]');
        collection[cat] = rules.filter(function(rule) {
          return !!rule;
        });
        hasInvalidRule = collection[cat].length !== rules.length;
      }
      if (hasInvalidRule) {
        localStorage.setItem(cat, JSON.stringify(rules));
      }
    }
  };
  hasCat = function(cat) {
    return ~cats.indexOf(cat);
  };
  getRules = function(cat) {
    var rules;
    rules = collection[cat];
    if (cat === 'custom') {
      return Object.keys(rules);
    } else {
      return rules;
    }
  };
  getRule4Show = function(cat, rule) {
    if (cat === 'custom') {
      return {
        ruleId: rule.url,
        rule: "<div>" + rule.matchUrl + "</div><div>" + rule.redirectUrl + "</div>",
        title: rule.matchUrl
      };
    } else {
      return {
        ruleId: rule,
        rule: rule,
        title: rule
      };
    }
  };
  getRules4Show = function(cat) {
    var k, ret, rules, v;
    rules = collection[cat];
    if (cat === 'custom') {
      ret = [];
      for (k in rules) {
        v = rules[k];
        ret.push({
          ruleId: v.url,
          rule: "<div>" + v.matchUrl + "</div><div>" + v.redirectUrl + "</div>",
          title: v.matchUrl
        });
      }
      return ret;
    } else {
      return rules.map(function(rule) {
        return {
          ruleId: rule,
          rule: rule,
          title: rule
        };
      });
    }
  };
  hasRule = function(cat, rule) {
    var rules;
    rules = collection[cat];
    if (!rules) {
      return false;
    }
    if (cat === 'custom') {
      return !!rules[rule.url];
    } else {
      return indexOf.call(rules, rule) >= 0;
    }
  };
  addRule = function(cat, rule) {
    var rules;
    if (!rule || hasRule(cat, rule)) {
      return false;
    }
    rules = collection[cat];
    if (cat === 'custom') {
      rules[rule.url] = rule;
    } else {
      rules.push(rule);
    }
    saveRule(cat);
    return true;
  };
  removeRule = function(cat, rules) {
    var _rules;
    _rules = getRules(cat);
    if (rules === void 0 || (Array.isArray(rules) && _rules.length === rules.length)) {
      collection[cat] = null;
    } else {
      if (!Array.isArray(rules)) {
        rules = [rules];
      }
      rules.forEach(function(rule) {
        var index;
        if (cat === 'custom') {
          delete collection[cat][rule];
        } else {
          index = _rules.indexOf(rule);
          _rules.splice(index, 1);
        }
      });
    }
    saveRule(cat);
  };
  setRestoreStatus = function(flag) {
    if (flag) {
      return localStorage.setItem('_is_restoring_', 'processing');
    } else {
      return localStorage.removeItem('_is_restoring_');
    }
  };
  isRestoring = function() {
    return !!localStorage.getItem('_is_restoring_');
  };
  saveRule = function(cat) {
    var rules;
    rules = collection[cat];
    if (rules) {
      localStorage.setItem(cat, JSON.stringify(rules));
    } else {
      localStorage.removeItem(cat);
    }
    initCollection();
  };
  eachRule = function(cat, fn, context) {
    var rules;
    rules = collection[cat];
    if (!rules) {
      return;
    }
    rules.forEach(function(rule) {
      if (rule !== void 0) {
        fn.call(context, rule);
      }
    });
  };
  getSwitch = function(cat) {
    var onoff;
    onoff = JSON.parse(localStorage.getItem('onoff') || '{}');
    return !!onoff[cat];
  };
  setSwitch = function(cat, isOn) {
    var onoff;
    onoff = JSON.parse(localStorage.getItem('onoff') || '{}');
    onoff[cat] = !!isOn;
    localStorage.setItem('onoff', JSON.stringify(onoff));
  };
  getConfig = function(key) {
    var config;
    config = JSON.parse(localStorage.getItem('config') || '{}');
    return config[key];
  };
  setConfig = function(key, val) {
    var config;
    config = JSON.parse(localStorage.getItem('config') || '{}');
    config[key] = val;
    localStorage.setItem('config', JSON.stringify(config));
  };
  getLocal = function(key, expectFormat) {
    switch (expectFormat) {
      case 'object':
      case 'o':
        return JSON.parse(localStorage.getItem(key) || '{}');
      case 'array':
      case 'a':
        return JSON.parse(localStorage.getItem(key) || '[]');
      default:
        return localStorage.getItem(key);
    }
  };
  setLocal = function(key, val) {
    localStorage.setItem(key, JSON.stringify(val));
    initCollection();
  };
  removeLocal = function(key) {
    localStorage.removeItem(key);
    initCollection();
  };
  initCollection();
  return {
    _collection: collection,
    initCollection: initCollection,
    setRestoreStatus: setRestoreStatus,
    isRestoring: isRestoring,
    hasCat: hasCat,
    addRule: addRule,
    getRules: getRules,
    getRules4Show: getRules4Show,
    getRule4Show: getRule4Show,
    removeRule: removeRule,
    saveRule: saveRule,
    eachRule: eachRule,
    getLocal: getLocal,
    setLocal: setLocal,
    getSwitch: getSwitch,
    setSwitch: setSwitch,
    getConfig: getConfig,
    setConfig: setConfig
  };
});


//# sourceMappingURL=collection.js.map
