// Generated by CoffeeScript 1.10.0

/**
 * auto i18n the web page
 */
(function(window) {
  var elms, makeBtns, slice;
  slice = Array.prototype.slice;
  if (navigator.userAgent.indexOf('Macintosh') > -1) {
    makeBtns = slice.call(document.querySelectorAll('.make-qrcode'));
    makeBtns.forEach(function(btn) {
      btn.setAttribute('i18n-content', 'qr_make_mac_btn');
    });
  }
  elms = document.querySelectorAll('[i18n-content]');
  elms = slice.call(elms);
  elms.forEach(function(elm) {
    var msgId;
    if (msgId = elm.getAttribute('i18n-content')) {
      elm.innerHTML = chrome.i18n.getMessage(msgId) || 'Error:No Message';
    }
  });
  elms = document.querySelectorAll('[i18n-value]');
  elms = slice.call(elms);
  elms.forEach(function(elm) {
    var attrs;
    attrs = elm.getAttribute('i18n-value').split(';');
    attrs.forEach(function(attr) {
      attr = attr.split(':');
      if (attr.length > 1) {
        elm.setAttribute(attr[0].trim(), chrome.i18n.getMessage(attr[1].trim()) || 'Error:No values');
      }
    });
  });
})(window);


//# sourceMappingURL=i18n.js.map
