// Generated by CoffeeScript 1.7.1
(function() {
  var content, cunt, getEle, loadImg, makeQRCode, qrUrl, qrelm, qrimg, textArea;
  getEle = document.getElementById.bind(document);
  qrelm = getEle('qrcode-wrapper');
  qrimg = getEle('qrcode');
  cunt = getEle('letter-cunt');
  textArea = getEle('text');
  content = '';
  qrUrl = 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=';
  loadImg = function(url) {
    var classList, imgElm;
    imgElm = document.createElement('img');
    classList = qrimg.parentElement.classList;
    classList.remove('error', 'loaded');
    imgElm.onerror = function() {
      classList.add('error');
      return classList.remove('loaded');
    };
    imgElm.onload = function() {
      qrimg.src = url;
      classList.remove('error');
      classList.add('loaded');
      return imgElm = null;
    };
    imgElm.src = url;
  };
  chrome.tabs.query({
    active: true,
    lastFocusedWindow: true
  }, function(tabs) {
    content = tabs[0].url;
    textArea.value = content;
    return loadImg(qrUrl + encodeURIComponent(content));
  });
  makeQRCode = function() {
    var encoded, textWrapper, tooLong;
    encoded = '';
    getEle('prompt').innerHTML = chrome.i18n.getMessage('pop_get_new');
    encoded = encodeURIComponent(text.value);
    textWrapper = getEle('text-wrapper');
    tooLong = getEle('long-error');
    if (encoded.length > 1900) {
      textWrapper.classList.add('error');
      tooLong.removeAttribute('hidden');
      setTimeout(function() {
        textWrapper.classList.remove('error');
        return tooLong.setAttribute('hidden');
      }, 3000);
      return;
    }
    loadImg(qrUrl + encoded);
    textWrapper.classList.remove('focus');
    qrelm.style.display = 'block';
    getEle('ntwk-error').setAttribute('hidden', true);
    getEle('action-tip').innerText = chrome.i18n.getMessage('pop_action_tip');
    return qrelm.focus();
  };
  qrelm.addEventListener('dblclick', function(e) {
    var textWrapper;
    getEle('prompt').innerText = chrome.i18n.getMessage('pop_edit_promp');
    getEle('action-tip').innerText = chrome.i18n.getMessage('pop_edit_tip');
    this.style.display = 'none';
    textWrapper = getEle('text-wrapper');
    textWrapper.classList.add('focus');
    cunt.innerText = "" + content.length + "/300";
    textArea.select();
    return textArea.focus();
  }, false);
  textArea.addEventListener('keydown', function(e) {
    if ((e.ctrlKey || e.metaKey) && e.keyCode === 13) {
      return makeQRCode();
    }
  }, false);
  textArea.addEventListener('keyup', function(e) {
    return cunt.innerText = "" + (this.value.trim().length) + "/300";
  }, false);
  return getEle('make').addEventListener('click', makeQRCode, false);
})();


//# sourceMappingURL=popup.map
